### ISSUE TITLE
obvious grid in test result

### ISSUE THREAD

**Issue by yaoxinreaps** [TonyHongtaoWu/RainMamba#10]
作者你好，我用自己的测试数据得到的结果中很容易出现明显的块状现象，如下图所示：
![image](https://github.com/user-attachments/assets/e249e517-0b7c-49a5-985e-a02cce94aad9)
请问这可能是什么原因？有什么参数可以调整吗？

**Comment by TonyHongtaoWu** [comment]
原因：对输入视频的进行了256x256的crop和overlap操作，具体在code/VRDS/mmedit/models/derainers/DrainNet.py中的test_clip和test_video函数。最简单的方法可以调整tile_overlap，例如tile_overlap = [1, 8, 8]。
如果想输入完整分辨率的图片需要调整tile = [5, 256, 256]到合适的[帧数，高，宽]。同时需要调整下面两个函数的nf, H 和 W值，来生成新的希尔伯特曲线，可以参考 https://github.com/TonyHongtaoWu/RainMamba/issues/1 。
def hilbert_curve_large_scale(self, ):
def hilbert_curve_small_scale(self, ):

**Comment by yaoxinreaps** [comment]
不好意思前段时间暂停了，我今天试了一下只改tile_overlap好像没用。我自己的视频分辨率跟VRDS是一样的，不知道为什么VRDS的结果基本看不出块状。另外，如果改tile的话，需要将宽高往小调还是往大调？谢谢~

**Comment by TonyHongtaoWu** [comment]
你测试的视频分辨率是多少呢？
可以试试把宽和高换成和输入视频一样的大小。
