### ISSUE TITLE
Some question 

### ISSUE THREAD

**Issue by csjingyu** [TonyHongtaoWu/RainMamba#6]
Hello, thank you for your work.
I have encountered a bug in training and would like to ask how to solve it.

AttributeError: 'MMDistributedDataParallel' object has no attribute '_use_replicated_tensor_module'

**Comment by TonyHongtaoWu** [comment]
You can fix it by following [this](https://github.com/microsoft/Cream/issues/179).

try to replace
File "envs/RainMamba/lib/python3.9 /site-packages/torch/nn/parallel/distributed.py", line 160, in _run_ddp_forward
module_to_run = self._replicated_tensor_module if
self._use_replicated_tensor_module else self.module
with
module_to_run = self.module
