### ISSUE TITLE
Error in Installing Bi-Mamba layer

### ISSUE THREAD

**Issue by yaoxinreaps** [TonyHongtaoWu/RainMamba#9]
Hi, when I install the environment at step 4, there comes the error as below:
![error](https://github.com/user-attachments/assets/caf097db-db7e-44ed-9de3-88e3eb608461)
Would please help me?

**Comment by TonyHongtaoWu** [comment]
It seems that there is a problem with the ninja version. You can try reinstalling it with the following command.
pip uninstall ninja
pip install ninja==1.11.1.1

**Comment by yaoxinreaps** [comment]
> It seems that there is a problem with the ninja version. You can try reinstalling it with the following command. pip uninstall ninja pip install ninja==1.11.1.1

谢谢回复，现在环境安装成功了，但是在跑VRDS测试的时候又报了下面的错误：
![image](https://github.com/user-attachments/assets/7cf4bb74-f821-4d8d-a904-37c5e902dd77)
而且前面还有一些其他错误和警告，如下图：
![image](https://github.com/user-attachments/assets/f960d573-329d-4dbc-a92f-e206b665a184)
能麻烦再帮忙看下吗？是不是哪个模块的版本不对？

**Comment by TonyHongtaoWu** [comment]
第一个问题可以参考这个回复
https://github.com/TonyHongtaoWu/RainMamba/issues/6
第二个图中框出的警告不影响结果

**Comment by yaoxinreaps** [comment]
> 第一个问题可以参考这个回复 #6 第二个图中框出的警告不影响结果

非常感谢，可以跑起来了。
